version: '3.3'
services:
  lab03:
    image: "lab03"
    build:
      context: .
      dockerfile: ./src/main/docker/Dockerfile
    ports:
      - 8888:8888
    volumes:
      - ./config-server.jks:/config-server.jks
    environment:
      GIT_URI: "https://github.com/mzegarras/tci-config-dev.git"
      GIT_USER: "mzegarra"
      GIT_PWD: ""
      KEYSTORE_PWD: "YOU_KEYSTORE_PASSWORD"
      KEYSTORE_ALIAS: "YOU_CONFIG_SERVER_KEY"
      KEYSTORE_SECRET: "YOU_KEYSTORE_PASSWORD"