apiVersion: v1
kind: Service
metadata:
  name: customers
  labels:
    app: customers
spec:
  ports:
    - port: 7070
      targetPort: 7070
  selector:
    app: customers
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customers
spec:
  selector:
    matchLabels:
      app: customers
  replicas: 1
  template:
    metadata:
      labels:
        app: customers
    spec:
      containers:
        - name: customers
          image: mzegarra/customer:1.0.0
          imagePullPolicy: Always #IfNotPresent #Always
          ports:
            - containerPort: 7070