---
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: backend
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: mzegarra/backend:1.0.0
          imagePullPolicy: Always #IfNotPresent #Always
          ports:
            - containerPort: 3000
          env:
          - name: URL_DB
            value: 'mongodb://mongo:27017/interfaces'
          - name: URL_DB_USER
            value: root
          - name: URL_DB_PWD
            value: "pwd123456!"